**Steps for Fine tuning :**
###1:   Perpare the dataset
###2:   Load pre-trained tokenizer, call it with dataset --> encoding
###3:   Build pytorch dataset
###4:   Load pre-trained model
###5A:  Load trainer and train it
###5B:  or use native pytorch training pipeline

In [4]:
import torch
from torch.utils.data import Dataset
from transformers import DistilBertTokenizerFast , DistilBertForSequenceClassification
from transformers import  trainer, training_args

model_name = "Distilbert-base-uncased"


#http://ai.stanford.edu/~amaas/data/sentimnt/

 prediction the Sentiment-analysis using pre-trained models

In [ ]:
def read_imdb_split(split_dir)
  split_dir = Path(split_dir)
  texts = []
  labels = []
  for label_dir in ['pos',"neg"]:
    for text_file in (split_dir/label_dir).iterdir():
      texts.append(text_file.read_text())
      labels.append(0 if label_dir == "neg" else 1)
  return texts, labels

  #Large movie Dataset

  train_texts, train_labels = read_imdb_split('acLImbd/train')
  test_tests, test_labels = read_imdb_split('acLImdb/test')

  train_texts, val_texts, train_labels, val_labels  = train_test_split(train_texts, train_labels, test_size = 0.2)

  class ImdbDataset(Dataset):
    def __init__(self, encodings, labels):
      self.encodings = encodings
      self.labels = labels

    def __getitem__(self, idx):
      item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
      item["labels"] = torch.tensor(self.labels[idx])
      return item

    def __len__(self):
      return len(self.labels)


tokenizer = DistisbertTokenizerfast.from_pretrained(model_name)

#ensure that all the sequences are padded to the same length and are truncated to be no longer than the model's max input length
#This will allow us to feed batches of sequences into the model at the smae time

train_encodings = tokenizer(train_texts, truncation = True, padding = True)
val_dataset = tokenizer(val_texts, truncation = True, padding = True)
test_dataset = tokenizer(test_texts, truncation = True, padding = True)

train_dataset = ImdbDataset(train_encodings, train_labels)
val_dataset = ImdbDataset(val_encodings, val_labels)
test_dataset = ImdbDataset(test_encodings, test_labels)

training_args = TrainingArguments(
                                  output_dir = './results', 
                                  num_train_epochs = 2, 
                                  per_device_train_batch_size = 16, 
                                  per_device_val_batch_size = 64, 
                                  warmup _steps = 500,
                                  learning_rate = 5e-5,
                                  weigth_Decay = 0.01,
                                  logging_dir = './logs',
                                  logginf_steps = 10
                                  )

model = TFDistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
trainer = trainer(
    model = model,
    args = training_args,
    train_dataset = train_dataset,
    val_dataset = test_dataset
)

trainer.train()






In [ ]:
## or train pytorch naitve

from torch.utils.data import DataLoader
from transformers import AdamW

leanring_rate = 5e-5

device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
model = TFDistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
model.to(device)
model.train()

train_loader = DataLoader(train_dataset, batch_size = 16, shuffle = True)
optim = Adam(model.parameter(), lr = learning_rate)

num_train_epochs = 2
for epoch in range(num_train_epochs):
  for batch in train_loader:
    optim.zero_grad()
    input_ids =  batch['inout_ids'].to(device)
    attention_mask = batch['attention_mask'].to(device)

    outputs = model(input_ids, attention_mask = attention_mask, labels = labels)
    loss = outputs[0]
    loss.backwards()
    optim.step()

model.eval()







In [3]:
#https://huggingface.co/models
!pip install transformers

     |████████████████████████████████| 3.1 MB 8.1 MB/s 
     |████████████████████████████████| 895 kB 48.5 MB/s 
     |████████████████████████████████| 3.3 MB 41.9 MB/s 
     |████████████████████████████████| 596 kB 39.8 MB/s 
     |████████████████████████████████| 56 kB 5.0 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [2]:
from transformers import pipeline, AutoTokenizer, TFDistilBertModel

import torch
import torch.nn.functional as F

# print(1)
# model = TFDistilBertModel.from_pretrained('distilbert-base-uncased')
# print(2)
# tokenizer = AutoTokenizer.from_pretrained('distilbert-base-uncased', pad_to_max_length=True)
# print(3)
# classifier = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)
classifier = pipeline("sentiment-analysis")

# result = classifier( "I am very happy learning huggingface transformers." )

results = classifier(["I am very happy learning huggingface transformers." , 
                        "I hate having to explain myself."])

# print(result)

for result in results:
    print(result)

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)


Downloading:   0%|          | 0.00/629 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/255M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


{'label': 'POSITIVE', 'score': 0.9996916055679321}
{'label': 'NEGATIVE', 'score': 0.9965311884880066}


In [3]:
from transformers import pipeline, AutoTokenizer, TFDistilBertModel

import torch
import torch.nn.functional as F

model_name = "distilbert-base-uncased-finetuned-sst-2-english"

# model = TFDistilBertModel.from_pretrained('distilbert-base-uncased')

# tokenizer = AutoTokenizer.from_pretrained('distilbert-base-uncased', pad_to_max_length=True)

classifier = pipeline("sentiment-analysis", model=model_name)


results = classifier(["I am very happy learning huggingface transformers." , 
                        "I hate having to explain myself."])

for result in results:
    print(result)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


{'label': 'POSITIVE', 'score': 0.9996916055679321}
{'label': 'NEGATIVE', 'score': 0.9965311884880066}


In [4]:
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification

import torch
import torch.nn.functional as F

model_name = "distilbert-base-uncased-finetuned-sst-2-english"

model = AutoModelForSequenceClassification.from_pretrained(model_name)

tokenizer = AutoTokenizer.from_pretrained(model_name)

classifier = pipeline("sentiment-analysis", model=model,tokenizer=tokenizer)


results = classifier(["I am very happy learning huggingface transformers." , 
                        "I hate having to explain myself."])

for result in results:
    print(result)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


{'label': 'POSITIVE', 'score': 0.9996916055679321}
{'label': 'NEGATIVE', 'score': 0.9965311884880066}


In [5]:
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification

import torch
import torch.nn.functional as F

model_name = "distilbert-base-uncased-finetuned-sst-2-english"

model = AutoModelForSequenceClassification.from_pretrained(model_name)

tokenizer = AutoTokenizer.from_pretrained(model_name)

classifier = pipeline("sentiment-analysis", model=model,tokenizer=tokenizer)


results = classifier(["I am very happy learning huggingface transformers." , 
                        "I hate having to explain myself."])

for result in results:
    print(result)



tokens = tokenizer.tokenize("I am very happy learning huggingface transformers.")
print("Tokens:" , tokens)
token_ids = tokenizer.convert_tokens_to_ids(tokens)
print("Token ids :" , token_ids)
token_ids = tokenizer("I am very happy learning huggingface transformers.")
print("input ids :" , token_ids)
# 101 & 102 is the begining and end of string

X_train = ["I am very happy learning huggingface transformers." , 
                        "I hate having to explain myself."]

batch = tokenizer(X_train,  padding = True , truncation= True, max_length = 512, return_tensors= "pt")




print(batch)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


{'label': 'POSITIVE', 'score': 0.9996916055679321}
{'label': 'NEGATIVE', 'score': 0.9965311884880066}
Tokens: ['i', 'am', 'very', 'happy', 'learning', 'hugging', '##face', 'transformers', '.']
Token ids : [1045, 2572, 2200, 3407, 4083, 17662, 12172, 19081, 1012]
input ids : {'input_ids': [101, 1045, 2572, 2200, 3407, 4083, 17662, 12172, 19081, 1012, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
{'input_ids': tensor([[  101,  1045,  2572,  2200,  3407,  4083, 17662, 12172, 19081,  1012,
           102],
        [  101,  1045,  5223,  2383,  2000,  4863,  2870,  1012,   102,     0,
             0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])}


In [6]:
#disables the gradient feature from the pytorch model
with torch.no_grad():
  #unpacks the values from the dictionary
  outputs = model(**batch)
  # in tensorflow its only model(batch) --- outputs only raw values (have to use soft max to fetch the predcitions)
  print(outputs)

  # in order the see the loss ----- > outputs = model(**batch, labels = torch.tensor([1,0]))

SequenceClassifierOutput(loss=None, logits=tensor([[-3.9160,  4.1678],
        [ 3.0733, -2.5871]]), hidden_states=None, attentions=None)


In [7]:
predictions = F.softmax(outputs.logits, dim = 1)
print(predictions)

# argmax gives the value of the highest value 
labels = torch.argmax(predictions, dim = 1)
print(labels)
#convertin labels into list
labels = [model.config.id2label[label_id] for label_id in labels.tolist()]
print(labels)

# outputs contains a sequence classifier || automodel for sequence classification 

tensor([[3.0840e-04, 9.9969e-01],
        [9.9653e-01, 3.4688e-03]])
tensor([1, 0])
['POSITIVE', 'NEGATIVE']


In [8]:
 save_directory = "saved"
 tokenizer.save_pretrained(save_directory)
 model.save_pretrained(save_directory)


 tokenizer = AutoTokenizer.from_pretrained(save_directory)
 model = AutoModelForSequenceClassification.from_pretrained(save_directory)


In [25]:
model_name = "oliverguhr/german-sentiment-bert"
model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

X_train_German = ["Das ist nicht fair", "Das war gut!", "Ohne gutes Ergebnis" , " Sie fährt ein blaues Auto"]
# NEGATIVE  POSITIVE NEGATIVE NEUTRAL

batch = tokenizer(X_train_Gemman, padding = True , truncation= True, max_length = 512)
batch = torch.tensor(batch["input_ids"])
print(batch) 

# if your using pytorch then use ---> batch = return_tensors= "pt" and model(batch) and delete this --> batch = torch.tensor(batch["input_ids"])
with torch.no_grad():
  outputs = model(batch)
  label_ids = torch.argmax(outputs.logits, dim = 1)
  print(label_ids)
  labels = [model.config.id2label[label_id] for label_id in label_ids.tolist()]
  print(labels)







tensor([[    3,   295,  4299,   149, 20716,     4,     0,     0,     0,     0,
             0],
        [    3,   295,   185,  1522, 26982,     4,     0,     0,     0,     0,
             0],
        [    3,   304,    96,  1935,  5569,  2011,     4,     0,     0,     0,
             0],
        [    3,    24, 26946, 26897,  5137, 26901,   155,  8516,  4874, 26910,
             4]])
tensor([1, 0, 0, 2])
['negative', 'positive', 'positive', 'neutral']
